### ISSUE TITLE
自定义购买数量

### ISSUE THREAD

**Issue by wcdfilll** [StarsDream00/LiteLoaderScriptPlugins#1]
据我看，应在json中增加一个属性，以便在购买商品时可以调整数量。例如：我想买64块土地，那么价格只有5个金币。如果当前商店无法做到这一点，那么长期来看，玩家的钱将会非常多，而且有助于替代使用十进制数字(0.00??)来表示每个商品的价格。我相信作者清楚这一点的重要性。
![image](https://user-images.githubusercontent.com/53313122/232565643-dd8e4389-efb8-4ed4-acdb-632123c32d25.png)

**Comment by StarsDream00** [comment]
I can't understand what you said, please use English or so.

**Comment by StarsDream00** [comment]
if you mean _use decimals as the price_, this plugin has this function

**Comment by StarsDream00** [comment]
are you talking about my plugin？

**Comment by wcdfilll** [comment]
> are you talking about my plugin？

no, what I mean is that the plugin should have a special feature that other plugins don't have. Admin will prescribe a certain amount for an item with any price, doing so to tighten the economy.

**Comment by StarsDream00** [comment]
please repeat your needs in English, i still can't understand what you need...

**Comment by wcdfilll** [comment]
> please repeat your needs in English, i still can't understand what you need...

It means that, for convenience, the shop should allow for listing the selling price for a specific quantity of the product. For example, the shop can sell 64 blocks of land with a purchase price of $50, and the selling price for each block of land will be $5. This will help avoid using decimal prices for each product. Currently, the plugin does not support this feature.

**Comment by StarsDream00** [comment]
> > please repeat your needs in English, i still can't understand what you need...
> 
> 
> 
> It means that, for convenience, the shop should allow for listing the selling price for a specific quantity of the product. For example, the shop can sell 64 blocks of land with a purchase price of $50, and the selling price for each block of land will be $5.
> 
>  This will help avoid using decimal prices for each product. Currently, the plugin does not support this feature.
> 
>  
> 
>  Chinese:
> 
>  这意味着，为了方便起见，商店应允许列出特定数量产品的销售价格。例如，商店可以以50美元的购买价格销售64个土块，每个土块的销售价格为5美元。这将有助于避免使用每个产品的小数价格。目前，该插件不支持此功能。

Do you mean to _use a special price when the quantity reaches a certain value_, or _only sell multiples of a certain number_?

**Comment by StarsDream00** [comment]
try [26f42b3](https://github.com/StarsDream00/LiteLoaderScriptPlugins/commit/26f42b3331c9e062c1df7e03df823d4f3ca4a903), i added a field called `num` for item to realize the function you want

**Comment by wcdfilll** [comment]
> 

![image](https://user-images.githubusercontent.com/53313122/233774699-e94b2136-517f-4637-8757-1c4b0c1218eb.png)
![image](https://user-images.githubusercontent.com/53313122/233774730-3b901194-1792-4f29-a9a5-c9ac0738163b.png)

**Comment by StarsDream00** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/53313122/233774699-e94b2136-517f-4637-8757-1c4b0c1218eb.png) ![image](https://user-images.githubusercontent.com/53313122/233774730-3b901194-1792-4f29-a9a5-c9ac0738163b.png)

Fixed in [31b3030](https://github.com/StarsDream00/LiteLoaderScriptPlugins/commit/31b30308f4c815bf2d0639df091af64dcb43a58b)

**Comment by wcdfilll** [comment]
> > > 
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/53313122/233774699-e94b2136-517f-4637-8757-1c4b0c1218eb.png) ![image](https://user-images.githubusercontent.com/53313122/233774730-3b901194-1792-4f29-a9a5-c9ac0738163b.png)
> 
> Fixed in [31b3030](https://github.com/StarsDream00/LiteLoaderScriptPlugins/commit/31b30308f4c815bf2d0639df091af64dcb43a58b)

![image](https://user-images.githubusercontent.com/53313122/233780380-1cd8cbb9-b8b0-4652-9047-03601477b6ca.png)
Cannot purchase 64 items at once, and after purchasing, it does not return the desired quantity of items.

**Comment by wcdfilll** [comment]
> > > 
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/53313122/233774699-e94b2136-517f-4637-8757-1c4b0c1218eb.png) ![image](https://user-images.githubusercontent.com/53313122/233774730-3b901194-1792-4f29-a9a5-c9ac0738163b.png)
> 
> Fixed in [31b3030](https://github.com/StarsDream00/LiteLoaderScriptPlugins/commit/31b30308f4c815bf2d0639df091af64dcb43a58b)

![image](https://user-images.githubusercontent.com/53313122/233780563-5f1f5a55-34c4-4eb9-a788-7574da565b27.png)
Cannot purchase 64 items at once, and after purchasing, it does not return the desired quantity of items.

**Comment by wcdfilll** [comment]
To modify the code so that players have to purchase a fixed quantity of products, we need to change the `sellConfirm` function. Instead of allowing players to input a quantity, we will default the quantity of products to be purchased to the value of `num` in the JSON file. Then, we will calculate the total cost based on this default quantity of products and the price of the product in the JSON file.

**Comment by StarsDream00** [comment]
> > > > 
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/53313122/233774699-e94b2136-517f-4637-8757-1c4b0c1218eb.png) ![image](https://user-images.githubusercontent.com/53313122/233774730-3b901194-1792-4f29-a9a5-c9ac0738163b.png)
> > 
> > 
> > Fixed in [31b3030](https://github.com/StarsDream00/LiteLoaderScriptPlugins/commit/31b30308f4c815bf2d0639df091af64dcb43a58b)
> 
> ![image](https://user-images.githubusercontent.com/53313122/233780563-5f1f5a55-34c4-4eb9-a788-7574da565b27.png) Cannot purchase 64 items at once, and after purchasing, it does not return the desired quantity of items.

full fixed in 499142b

**Comment by wcdfilll** [comment]
> > > > > 
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/53313122/233774699-e94b2136-517f-4637-8757-1c4b0c1218eb.png) ![image](https://user-images.githubusercontent.com/53313122/233774730-3b901194-1792-4f29-a9a5-c9ac0738163b.png)
> > > 
> > > 
> > > Fixed in [31b3030](https://github.com/StarsDream00/LiteLoaderScriptPlugins/commit/31b30308f4c815bf2d0639df091af64dcb43a58b)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/53313122/233780563-5f1f5a55-34c4-4eb9-a788-7574da565b27.png) Cannot purchase 64 items at once, and after purchasing, it does not return the desired quantity of items.
> 
> full fixed in [499142b](https://github.com/StarsDream00/LiteLoaderScriptPlugins/commit/499142b94991520f569cbcc88123071ddf7f9309)

give me 1 day to test, have error I will report back, working now. Sincere thanks to the author

**Comment by wcdfilll** [comment]
Error in `recycleshop` (minor error):
-> When I want to sell an item to the shop, for example: "I set the value of `num: 64`, if I try to sell when I only have exactly 64 items in my inventory, the shop will not allow the sale. But if I have x2 items in my inventory, that is `64x2=128(2 stacks)`, then I can sell them."
![image](https://user-images.githubusercontent.com/53313122/233795855-2c0f1481-51de-430a-8722-16c4cb6eb55f.png)

**Comment by StarsDream00** [comment]
> Error in `recycleshop` (minor error):
> 
> -> When I want to sell an item to the shop, for example: "I set the value of `num: 64`, if I try to sell when I only have exactly 64 items in my inventory, the shop will not allow the sale. But if I have x2 items in my inventory, that is `64x2=128(2 stacks)`, then I can sell them." 
> 
> Error return notice below:
> 
> ![image](https://user-images.githubusercontent.com/53313122/233795855-2c0f1481-51de-430a-8722-16c4cb6eb55f.png)
> 
> 

fixed in 5cde17e6352ccf13711faf6128c2389f642a0a94
