### ISSUE TITLE
Difficult to manipulate

### ISSUE THREAD

**Issue by wcdfilll** [StarsDream00/LiteLoaderScriptPlugins#2]
The shop supports item grouping and the ability to go back to the previous page, but there is an issue - if the Admin creates too many groups (around 3 to 4 groups), players are forced to go back to each previous page before they can exit the shop. The author has tested this situation ? And found that nested groups make it cumbersome to navigate back to the previous page. Solution: A button should be added to allow players to exit the form without going back to the previous page. What does the author think about this?

**Comment by StarsDream00** [comment]
i donnt really want to realize this feature🤔
please fork this repo and edit it as you want if you really need this
