### ISSUE TITLE
Shop: `dataValues`不可用

### ISSUE THREAD

**Issue by wcdfilll** [StarsDream00/LiteLoaderScriptPlugins#3]
![image](https://user-images.githubusercontent.com/53313122/234163401-fc5aa0fe-f741-496e-b7e0-b4262dd19d56.png)

**Comment by StarsDream00** [comment]
there seems to be no problem with my code🤔, it may come from LiteLoader

**Comment by StarsDream00** [comment]
i will check this out when i am free

**Comment by wcdfilll** [comment]
> 

Do you want i report bug to LL?

**Comment by StarsDream00** [comment]
> Do you want me to report bug to LL?

Wait first

**Comment by StarsDream00** [comment]
https://github.com/LiteLDev/LiteLoaderBDS/issues/1218

**Comment by wcdfilll** [comment]
I submitted the Ashop.js plugin, did the author receive it?

**Comment by StarsDream00** [comment]
> I submitted the Ashop.js plugin, did the author receive it?

i saw that, but what do you want me to do?

**Comment by wcdfilll** [comment]
> > I submitted the Ashop.js plugin, did the author receive it?
> 
> i saw that, but what do you want me to do?

their plugin doesn't seem to be crashing aux

**Comment by StarsDream00** [comment]
> > > I submitted the Ashop.js plugin, did the author receive it?
> 
> > 
> 
> > i saw that, but what do you want me to do?
> 
> 
> 
> their plugin doesn't seem to be crashing `aux`

i have read the usage for that plugin, and i donnt even know is the plugin supports aux

**Comment by wcdfilll** [comment]
> > > > I submitted the Ashop.js plugin, did the author receive it?
> > 
> > 
> > > 
> > 
> > 
> > > i saw that, but what do you want me to do?
> > 
> > 
> > their plugin doesn't seem to be crashing `aux`
> 
> i have read the usage for that plugin, and i donnt even know is the plugin support aux

maybe I'm wrong, I read config.json on minebbs and found it worth it
