### ISSUE TITLE
Crash client on mobile device when dragging the quantity increase/decrease slider for buying items (not selling)

### ISSUE THREAD

**Issue by wcdfilll** [StarsDream00/LiteLoaderScriptPlugins#4]
I was informed by a player that when they try to adjust the slider to increase/decrease the purchase amount on their mobile device, it crashes. This issue only occurs in the in-game store (not with items sold by players).
Proposed solution: Instead of calculating how much a player can purchase based on their total funds, we should implement a limit. Having too much money can result in an integer value that is too large for a 32-bit version.

**Comment by StarsDream00** [comment]
https://github.com/StarsDream00/LiteLoaderScriptPlugins/tree/fix/shop_crash
