### ISSUE TITLE
Crash error when dragging the quantity of items in the `buy shop`

### ISSUE THREAD

**Issue by wcdfilll** [StarsDream00/LiteLoaderScriptPlugins#5]
Thanh still encounters an error with the `buy item` quantity after fixing it. In the case where the player has 250,000 coins and buys an item with a quantity of 1 stack item corresponding to 50 coins for that corresponding stack item, the crash error still occurs. This has been tested on mobile but not yet on Windows.

**Comment by StarsDream00** [comment]
send me your data file

**Comment by wcdfilll** [comment]
> send me your data file
[data.zip](https://github.com/StarsDream00/LiteLoaderScriptPlugins/files/11532121/data.zip)

**Comment by StarsDream00** [comment]
this client crash may be caused by non-existent photos in your data file, try to remove them
